version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
            target: production
        ports:
            - "8000:8000"
        environment:
            - NODE_ENV=production
            - PORT=8000
        networks:
            - bitriel-network
        restart: unless-stopped

    web:
        build:
            context: .
            dockerfile: Dockerfile.web
            target: production
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - HOSTNAME=0.0.0.0
        networks:
            - bitriel-network
        restart: unless-stopped
        depends_on:
            - api

    docs:
        build:
            context: .
            dockerfile: Dockerfile.docs
            target: production
        ports:
            - "3001:3001"
        environment:
            - NODE_ENV=production
            - PORT=3001
            - HOSTNAME=0.0.0.0
        networks:
            - bitriel-network
        restart: unless-stopped

    # Development service (alternative to production services)
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
            - "3001:3001"
            - "8000:8000"
        environment:
            - NODE_ENV=development
        volumes:
            - .:/app
            - /app/node_modules
        networks:
            - bitriel-network
        profiles:
            - dev

networks:
    bitriel-network:
        driver: bridge
